main:
    #- country_id
    - name
    - iso_code

epi:
    - cases
    - deaths
    - recovered
    - new_cases
    - new_deaths
    - fatality_rate_percentage
    - cases_per_100000
    - deaths_per_100000
    - cases_per_1000_hospital_beds
    - deaths_per_1000_hospital_beds
    - cases_per_1000_nurses
    - deaths_per_1000_nurses
    - cases_per_1000_physicians
    - deaths_per_1000_physicians
    - days_since_outbreak
    - new_cases_percent_increase
    - avg_3d_new_cases_percent_increase
    - tests
    - tests_per_100000
    - new_cases_rolling_average_3
    - new_cases_rolling_average_7
    - new_cases_rolling_average_14
    - new_cases_rolling_average_21
    - new_deaths_rolling_average_3
    - new_deaths_rolling_average_7
    - new_deaths_rolling_average_14
    - new_deaths_rolling_average_21
    - stage_number
    - travel_risk_score
    - new_cases_per_100000
    - avg_7d_new_cases_per_100k
    
demography:
    - total_population_all
    - total_population_below_1
    - total_population_1_to_4
    - total_population_5_to_14
    - total_population_15_to_24
    - total_population_25_to_34
    - total_population_35_to_54
    - total_population_55_to_74
    - total_population_above_75
    - population_percentage_over_60
    
sanitary:
    - hospital_beds_per_1000
    - physicians_per_1000
    - nurses_per_1000

economic:
    to_drop:
        - unemployment_rate_2020_03_31 
        - unemployment_rate_2020_06_30 
        - unemployment_rate_2020_09_30 
        - unemployment_rate_2020_12_31
        - unemployment_rate_2021_03_31 
        - unemployment_rate_2021_06_30 
    to_use:
        - unemployment_rate_2021_09_30 
        - unemployment_rate_2021_12_31
        - unemployment_rate_2019_03_31 
        - unemployment_rate_2019_06_30 
        - unemployment_rate_2019_09_30 
        - unemployment_rate_2019_12_31
        - gdp_2019_03_31 
        - gdp_2019_06_30 
        - gdp_2019_09_30 
        - gdp_2019_12_31
        - gdp_2020_03_31 
        - gdp_2020_06_30 
        - gdp_2020_09_30 
        - gdp_2020_12_31
        - gdp_2021_03_31 
        - gdp_2021_06_30 
        - gdp_2021_09_30 
        - gdp_2021_12_31
        - fiscal_measures
        - emergency_investment_in_health_care
        - investment_in_vaccines
    
weather:
    - maxtempC
    - mintempC
    - tempC
    - FeelsLikeC
    - humidity
    - pressure
    - HeatIndexC
    - uvIndex
    - totalSnow_cm
    - sunHour
    - windspeedKmph
    - precipMM

mobi_google:
    to_drop:
        - mobility_google_retail_and_recreation
        - mobility_google_grocery_and_pharmacy
        - mobility_google_transit_stations
        - mobility_google_workplace
        - mobility_google_residential
        - mobility_google_index
    to_use:
        - mobility_google_retail_and_recreation_7d_avg
        - mobility_google_grocery_and_pharmacy_7d_avg
        - mobility_google_transit_stations_7d_avg
        - mobility_google_workplace_7d_avg
        - mobility_google_residential_7d_avg
    
policies:
    to_drop:
        - covid19_reopen_criteria_14_day_new_cases_downward_trajector
        - covid19_reopen_criteria_14_day_decreasing_deaths
        - has_implemented_introduction_of_quarantine_policies
        - has_implemented_public_services_closure
        - has_implemented_economic_measures
        - has_implemented_flights_suspension
        - has_implemented_schools_closure
        - has_implemented_border_closure
        - has_implemented_state_of_emergency_declared
        - has_implemented_general_lockdown
        - has_implemented_travel_restrictions
    to_use:
        - school_closing
        - workplace_closing
        - cancel_public_events
        - restrictions_on_gatherings
        - close_public_transport
        - stay_at_home_requirements
        - public_information_campaigns
        - testing_policy
        - vaccination_policy
        - contact_tracing
        - restrictions_on_internal_movement
        - international_travel_controls

vaccines:
    # FOR RL: ONLY POLICY
    to_use:
        - vaccines_available
        - Johnson&Johnson
        - Sputnik V
        - Pfizer/BioNTech
        - Oxford/AstraZeneca
        - EpiVacCorona
        - Sinopharm/Beijing
        - Moderna
        - Covaxin
        - Sinovac
        - Sinopharm/Wuhan
        - total_vaccinations
        - people_vaccinated
        - people_fully_vaccinated
        - daily_vaccinations
    
    #to_drop:
        
    

outcomes:
    to_drop:
        - epiforecasts_effective_reproduction_number_lower_50
        - epiforecasts_effective_reproduction_number_upper_50    
    to_use:
        - epiforecasts_effective_reproduction_number_median
        - epiforecasts_effective_reproduction_number_lower_90
        - epiforecasts_effective_reproduction_number_upper_90
        - new_deaths
    